# Generated by Django 4.0.4 on 2022-05-06 03:15

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=150), size=None),
        ),
    ]
