# Generated by Django 4.0.4 on 2022-05-06 03:21

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_description_remove_recipe_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=150), default=[], size=None),
        ),
    ]
